### ISSUE TITLE
Convert SemanticDB docstrings into LSIF hover messages

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#102]
This ticket will require changes inside and outside of this repo

* ~~scalameta/scalameta: add the [`documentation`](https://github.com/sourcegraph/lsif-java/blob/0d693a4f883ae71a5bf518d0e4803897102a900d/semanticdb-javac/src/main/protobuf/semanticdb.proto#L89-L91) field to the upstream SemanticDB spec.~~
* sourcegraph/lsif-semanticdb: use the new `documentation` field (will happen in rewrite to Java)
* ~~use new documentation field when emitting docstrings~~

**Comment by Strum355** [comment]
PR to address point 1: https://github.com/scalameta/scalameta/pull/2262

**Comment by Strum355** [comment]
Completed in #127, closing this issue
