### ISSUE TITLE
Remove system dependency on lsif-semanticdb

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#104]
Currently, `lsif-java` shells out to `lsif-semanticdb` to convert SemanticDB files into LSIF. This system dependency complicates the installation for `lsif-java` because `lsif-semanticdb` needs to be available on the `$PATH`.

It would be nice if we can remove this system dependency by implementing the SemanticDB->LSIF conversion in Java. Ideally, I'd like `lsif-java` to be distributed as a standalone native binary with batteries included. We already embed the compiler plugin and the java agent jars as resources. WDYT @efritz @Strum355?

**Comment by efritz** [comment]
I have no issues here. We only wrote it on go initially for code reuse with (what is now) lsif-protocol.

**Comment by Strum355** [comment]
![image](https://user-images.githubusercontent.com/18282288/109680264-42149500-7b74-11eb-8578-30226e8c0558.png)
Given we probably have 0 people using it currently (:raised_eyebrow:), this change will probably not affect anyone so Ive no issues either

**Comment by tjdevries** [comment]
Maybe we should write it in a language that can compile it to both :laughing: 

Nah, I'm kidding. That sounds like a good plan. Are we going to keep both implementations then? Can we have some shared spec of tests that they both pass, etc?

**Comment by olafurpg** [comment]
> Are we going to keep both implementations then? 

Good question. I suspect the Java implementation may diverge as the project evolves. It might make sense to deprecate/archive one of the implementations down the road.

**Comment by Strum355** [comment]
lsif-semanticdb lives in this repo now since #127
