### ISSUE TITLE
Add documentation website

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#107]
It would be nice if we can document lsif-java with a website instead of the readme. I personally like websites over READMEs because

* it's easier to dynamically generate content like version numbers for copy-paste installation instructions
* READMEs become difficult to navigate once they grow beyond a certain size

**Comment by sreeharsha201** [comment]
@olafurpg I am interested and willing to contribute ❤️

**Comment by olafurpg** [comment]
@sreeharsha201 Thank you for the offer! We just merged #112 which adds a new website, which is live at https://sourcegraph.github.io/lsif-java/
