### ISSUE TITLE
Incorrect range for interface definition

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#109]
https://github.com/sourcegraph/lsif-java/blob/756563ffca0a55d49141fc2c94d75af729c30744/tests/snapshots/src/main/generated/minimized/Interfaces.java#L3-L4

```diff
-- obtained
++ expected
  public interface Interfaces {
- //     ^^^^^^^^^^ definition minimized/Interfaces#
+ //               ^^^^^^^^^^ definition minimized/Interfaces#

```

**Comment by Strum355** [comment]
Issue also affects classes, not exclusive to interfaces 
![image](https://user-images.githubusercontent.com/18282288/109966559-51b4ea80-7ce8-11eb-8bbd-bd2209bd9599.png)

**Comment by olafurpg** [comment]
@Strum355 good catch!

A good place to start looking into this issue would be this file here https://github.com/sourcegraph/lsif-java/blob/756563ffca0a55d49141fc2c94d75af729c30744/semanticdb-javac/src/main/java/com/sourcegraph/semanticdb_javac/CompilerRange.java

We may be able to fix this issue by adding a new `CompilerRange` kind that handles this case for interface/class definition.
