### ISSUE TITLE
Implement SymbolInformation.overrides

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#113]
Currently, "find references" only returns results for the exact symbol over the cursor. The results don't include methods that override that symbol, or the supermethod of a symbol.

* implement the new `SymbolInformation.overrides` feature that got added to SemanticDB https://github.com/scalameta/scalameta/pull/2233
* extend lsif-semanticdb conversion to include `overrides` in the "find references" results

**Comment by Strum355** [comment]
Related to https://github.com/sourcegraph/sourcegraph/issues/15699.

First look indicates [JavacTypes.getOverridenMethods](https://www.javadoc.io/doc/org.kohsuke.sorcerer/sorcerer-javac/latest/com/sun/tools/javac/model/JavacTypes.html#getOverriddenMethods-javax.lang.model.element.Element-) may be a viable route. Will investigate

**Comment by Strum355** [comment]
Testing seems to confirm the previous comment

![image](https://user-images.githubusercontent.com/18282288/114472905-1660e200-9beb-11eb-9ba6-a372f96fcb32.png)
