### ISSUE TITLE
Occurrences for class type parameters are not emitted

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#122]
It looks like we're not emitting type parameters on classes

https://github.com/sourcegraph/lsif-java/blob/48bce73664383381c85211a781a427924abae1a2/tests/snapshots/src/main/generated/com/airbnb/epoxy/BaseEpoxyTouchCallback.java#L8

```diff
-- obtained
++ expected
  interface BaseEpoxyTouchCallback<T extends EpoxyModel> {
+                                  ^ definition com/airbnb/epoxy/BaseEpoxyTouchCallback#[T]
```

**Comment by Strum355** [comment]
Resolved in #125 and #129
