### ISSUE TITLE
Add documentation for how to upload LSIF index to Sourcegraph

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#143]
Our docs currently only cover the steps to generate the LSIF index.

**Comment by olafurpg** [comment]
Closing as wontfix. Uploading the index to Sourcegraph is the command `src lsif upload`

**Comment by kubukoz** [comment]
@olafurpg is there a particular reason why it couldn't be built into this project? It'd simplify the setup for e.g. github actions 😅
