### ISSUE TITLE
Add new Documentation.Format kind for Signatures, make repeated and upstream

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#145]
Followed on from https://github.com/sourcegraph/lsif-java/pull/131#discussion_r605485119.

Additional context:
This will allow us to not have to hijack SymbolInformation.display_name in the LSIF Snapshotting, instead giving an alternative way to encode a signature, as a rendered string as opposed to a typed tree

**Comment by olafurpg** [comment]
@Strum355 should we close this issue as fixed? The `Documentation.Format` enum has been upstreamed, but it's not repeated (which doesn't seem to be necessary for lsif-java). We can always make it repeated in the future while keeping protobuf binary compatibility.
