### ISSUE TITLE
Hover messages use `unknown_language` for docstrings

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#152]
It should be `markdown` instead.

https://github.com/sourcegraph/lsif-java/blob/debdbb2ba2a27cf45cbf81336730eb5903f0159b/lsif-semanticdb/src/main/java/com/sourcegraph/lsif_semanticdb/LsifSemanticdb.java#L120

```diff
-           markedStrings.add(new MarkedString(Semanticdb.Language.UNKNOWN_LANGUAGE, documentation));
+           markedStrings.add(new MarkedString("markdown", documentation));
```

**Comment by Strum355** [comment]
Superseded by #162
