### ISSUE TITLE
Provide index output for Maven (pom.xml) files

### ISSUE THREAD

**Issue by johnedmonds** [sourcegraph/lsif-java#20]
Not sure if this is the right place but I was hoping we could get the output to include indices for maven (pom.xml) files. For example, when you use a property like `${proto.version}` it would point back to where the property is defined in the `<properties>` section.

**Comment by olafurpg** [comment]
Thank you for reporting! Navigation for pom.xml files is currently outside of scope for this project. It's a good idea and absolutely worth implementing at some point, but I'm gonna close this ticket for now while we get this project off the ground :)
