### ISSUE TITLE
NullPointerException when trying to generate LSIF file

### ISSUE THREAD

**Issue by mr1chter** [sourcegraph/lsif-java#30]
Thank you for your efforts!
If we try to generate the index file via a gitlab CI job, a NullPointerException is thrown:
```
$ ~/lsif-java/build/install/lsifjava/bin/lsifjava -projectRoot . -out dump.lsif
Running JVM 11.0.6
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/datetime/DateTime.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/datetime/DateTimeFormats.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/test/java/myproject/shared/datetime/DateTimeTest.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/datetime/DateTimeType.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/datetime/TimeZoneData.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/filter/FilterCriterion.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/filter/FilterCriterionMatcher.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/test/java/myproject/shared/filter/FilterCriterionMatcherTest.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/test/java/myproject/shared/filter/FilterCriterionTest.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/filter/RegExpHelper.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/test/java/myproject/shared/filter/RegExpHelperTest.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/form/AbstractComponent.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/test/java/myproject/shared/form/AbstractComponentTestTemplate.java
Found /home/gitlab-runner/builds/mLw9xUbW/0/m.richter/mylibrary/src/main/java/myproject/shared/form/AbstractFormElement.java
Exception in thread "main" java.lang.NullPointerException
	at ProjectIndexer.index(ProjectIndexer.java:47)
	at Main.main(Main.java:16)
```

The next file would have been `[...]/myproject/shared/form/ApplicationSettings.java` and contentwise it does not have anything peculiar or different than the other files that would justify failure... no... hold on, My IDE tells me that the class inside is not used. This is not particularly surprising though, as this is only a library exposing some common functionality, but it does not show that for the other classes that are in the log above.

The project itself (can't share it, sorry) is a fairly standard gradle project of a java-only library to which i generate the `pom.xml` file as you documented in the README. The project has ~20kLOC of java.

Afaik we are running the latest version of lsif-java. I'll try to reproduce it locally as well and add a comment then.

**Comment by mr1chter** [comment]
I ran it locally using the master branch with both `-verbose` and `-debug` and the output was not different at all (not counting the different location of the project). I also noticed another thing:

> The next file would have been `[...]/myproject/shared/form/ApplicationSettings.java` and contentwise it does not have anything peculiar or different than the other files that would justify failure... no... hold on, My IDE tells me that the class inside is not used. This is not particularly surprising though, as this is only a library exposing some common functionality, but it does not show that for the other classes that are in the log above.

This is actually wrong, the next file would have been a test file (`[...]src/test/java/myproject/shared/form/AbstractFormElementTestTemplate.java`) which is very similar to the already listed `AbstractComponentTestTemplate.java` which apparently didn't cause any problems. They have the similar size, same structure and similar location. I don't know why one should work and the other wouldn't.

**Comment by Strum355** [comment]
Hi @mr1chter 

If you could apply the JVM flag `-XX:+ShowCodeDetailsInExceptionMessages` and send the resulting stacktrace which should contain some more info, that would be greatly appreciated.
Also please revisit the steps for converting from Gradle to Maven project [here](https://github.com/sourcegraph/lsif-java#step-1) to see if any changes need to be made on your side, as they've recently been updated, however I don't believe that they should have an affect on this issue. 

Thanks!

**Comment by mr1chter** [comment]
Thank you! I tried the altered gradle code but as expected, it didn't change anything. The Java option you describe is sadly a part of jdk14 and we're still using v11. My WSL/apt also can't get me jdk14 so I can't use that (should be 18.04).

But I did try to debug this further and it seems that `el.getPosition().getFile()` returned `null`, so calling `getPath()` on it fails. This seems somewhat consistent with the documentation in spoon, afair. But I don't know why it has no file assigned to it (yet).

**Comment by Strum355** [comment]
Thanks for the investigation! Unfortunately thats an issue we've seen crop up a number of times before. Its not easily obvious why this happens and is one of the contributing reasons why we are ultimately considering researching more stable alternatives to Spoon.

**Comment by olafurpg** [comment]
@mr1chter Thank you for reporting! Closing this ticket since it's no longer relevant. This project recently received a reboot and we're slowly ramping up support for more build tools and Java versions. I encourage you to subscribe to releases if you want to get notifications on our progress :)
