### ISSUE TITLE
Precise code intel support for Kotlin

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#304]
Currently, lsif-java supports indexing Java and Scala projects. We're working on a SemanticDB compiler plugin for Kotlin in the repo here https://github.com/sourcegraph/lsif-kotlin

Subscribe to this issue for notifications when `lsif-java index` can also index Kotlin projects in Gradle/Maven.

Subtasks

- [x] #338
- [x] #339
- [ ] #353
- [x] Update documentation for new Kotlin support https://github.com/sourcegraph/lsif-java/pull/354
- [x] Support auto-indexing for Kotlin package repos on sourcegraph.com https://github.com/sourcegraph/sourcegraph/pull/26284
- [x] #362

**Comment by olafurpg** [comment]
We just released https://github.com/sourcegraph/lsif-java/releases/tag/v0.6.11 with support for Kotlin Gradle builds. Please give it a try by installing `lsif-java` (instructions https://sourcegraph.github.io/lsif-java/docs/getting-started.html ) and run `lsif-java index`.

**Comment by yinquanteo** [comment]
@olafurpg, @scalabilitysolved: I renamed this issue and added it to [this dashboard](https://github.com/orgs/sourcegraph/projects/214/views/11). Let me know if you preferred if we took a different approach. 

@scalabilitysolved / @macraig Also, I noticed that this issue is closed. Are we technically considering adding Koitlin done for the purposes of our Q4 goal?

**Comment by scalabilitysolved** [comment]
Kotlin hovers are the last item needing to be implemented before we'll consider Kotlin GA for our Q4 goal.

**Comment by olafurpg** [comment]
Closing this since lsif-java v0.7.2 now supports hover messages for Kotlin 💪 Issue  #353 is still open, but it's not blocking GA. We can add support for Maven Kotlin projects if there is demand for it.

**Comment by jyavorska** [comment]
Congrats team on completing the first Q4 OKR!
