### ISSUE TITLE
Method reference is not broken into sections

### ISSUE THREAD

**Issue by Arthurm1** [sourcegraph/lsif-java#307]
Using version: 0.5.7

In the below code in VSCode, clicking anywhere on `this.getThis()::supplyFoo` results in the whole section being highlighted and using `goto` results in navigating to the `supplyFoo` method only.

I'd expect to be able to highlight the individual sections (`this`, `getThis()` and `supplyFoo`) and navigate to the `getThis()` method when I click on that section.

This works fine in method `createFoo` but not in `createFooUsingMethodReference`

I've just assumed this is down to lsif-java, not VSCode/Metals

```java
package Bar;

import java.util.function.Supplier;

public class Foo {

    public Foo supplyFoo() {
        return new Foo();
    }

    public Foo getThis() {
        return this;
    }

    public Foo createFoo() {
        return this.getThis().supplyFoo();  // <- clicking on `supplyFoo` highlights `supplyFoo`
    }

    public Supplier<Foo> createFooUsingMethodReference() {
        return this.getThis()::supplyFoo;   // <- clicking on `supplyFoo` highlights `this.getThis()::supplyFoo`
    }
}
```

**Comment by Strum355** [comment]
Thanks for the report :slightly_smiling_face: the fix for this will be in the next release!
