### ISSUE TITLE
Potential for numerous files to be missed on indexing

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#35]
This is a multi (at least 2) tiered issue.

1. Spoons handling of finding source directories defined in pom.xml needs to be improved. Two issues found:
	1. If a module/pom file doesn't specify `<sourceDirectory>` and/or `<testSourceDirectory>`, it falls back to a default for whichever were missing (`src/main/java` and `src/test/java` respectively), even if they would be defined in an ancestor up the pom hierarchy. This issue at the time of writing has been addressed locally, PR incoming soon:tm:
	Ref: [POM inheritance](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Inheritance)
	2. Spoon doesn't interpolate `${project.basedir}`, which was encounted in some repos. PR mentioned above will also address this.
2. Theory: in multi-maven-project scenarios (>1 pom.xml file in a repo), in root pom files that don't act as aggregators (aka don't define a `<module>` block), maven projects that aren't the root project would be missed, and therefore not indexed. This could be addressed in lsif-java itself by comparing the discovered-by-Spoon projects and comparing it to the discovered-by-filesystem-tree-walking pom.xml files/projects, and adding the missing projects to the Spoon model's input resources.
	Ref: [POM aggregation](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#project-aggregation)

**Comment by Strum355** [comment]
PR created @ https://github.com/INRIA/spoon/pull/3562

**Comment by macraig** [comment]
@Strum355 is this still relevant after switching away from Spoon?

**Comment by olafurpg** [comment]
Closing this since it's no longer relevant
