### ISSUE TITLE
case classes and companion objects

### ISSUE THREAD

**Issue by Kelvin-Lee** [sourcegraph/lsif-java#396]
`lsif-java` version: `0.7.2`

**Type of code:** case classes

**Expected behavior:** Instantiations of case classes should reference the case class definition in precise code intelligence. This is consistent with IntelliJ behavior.

**Actual behavior:** If a companion object is not defined, code intelligence falls back to search-based code intelligence. If a companion object is defined, code intelligence references the companion object instead.

```
case class Test(a: String) {}
```

```
case class Test(a: String) {}
object Test {}
```

**Comment by olafurpg** [comment]
Thank you for reporting! I left a comment in #397 explaining the root cause, which applies to this issue as well.
