### ISSUE TITLE
Case Class "Find References" Finds All Case Class Definitions

### ISSUE THREAD

**Issue by wchau** [sourcegraph/lsif-java#399]
`lsif-java` version: `0.7.5`

Type of code: case classes in Scala

Expected behavior: Case class "Find Reference" should only include usage of the case class in precise code intelligence.

Actual behavior: Case class "Find References" includes ALL case class definitions in precise code intelligence. This could have been due to the fix in https://github.com/sourcegraph/lsif-java/issues/396 introducing this new bug.

```
case class TestA(a: String) {}

case class TestB(a: String) {}
```

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. It's indeed related to the bugfixes for v0.7.5, the results are showing references for the auto-generated case class methods that override methods from `scala.Product`. Find references on an overridden method includes usages of the overridden symbol. I estimate this is  fairly easy to fix.

**Comment by olafurpg** [comment]
I just triggered a v0.7.6 release with the bugfixes for this issue and a few other case class related issues (see #401). It may take a couple of hours for the artifacts to become available on Maven Central

**Comment by olafurpg** [comment]
Confirming that I'm unable to reproduce this issue with SCIP.
