### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#42]
Move away from getting users to have to generate a Maven project from a Gradle project with fiddly Groovy scripts. We demand native support :anger: 

Direction will be dependent on results of [RFC 238](https://docs.google.com/document/d/1UYSS3U6m1BOIZqPegd2LlcWZ_pOIfOgdQ0u3fqUEDBg/edit#)

**Comment by Strum355** [comment]
For a first quick pass (without invoking gradle programmatically), consider: https://github.com/sourcegraph/java-langserver/blob/master/src/main/java/com/sourcegraph/langserver/langservice/gradle/Fradle.java

**Comment by Strum355** [comment]
Went with Gradle Tooling API approach. Appears to work well for both single-project and multi-project gradle configurations :+1: 

Appears to not work in certain situations e.g. when `java` plugin is not in use. Oh well

**Comment by Strum355** [comment]
Closing issue as it "works". Further tracking issues will be created for individual issues encountered as they occur

**Comment by aidaeology** [comment]
@Strum355 Yay! Glad to see there's now native support for Gradle projects.
