### ISSUE TITLE
lsif-java on master no longer indexes Spoon

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/lsif-java#44]
As of 2de844423a3d94075b845b9d18b30b883b8b967c a commit introduced a regression that causes `lsif-java` to spin forever (>5 hours on GH action) when indexing the Spoon repository. [Example](https://github.com/INRIA/spoon/runs/1142710290). I've reverted the lsif-java-action to use the last known good commit for indexing Spoon, since it currently uses `lsif-java` in their CI: https://github.com/sourcegraph/lsif-java-action/commit/11dd91b4cba0f2a143914b14162d27d202f6726e. Context from [spoon thread](https://github.com/INRIA/spoon/pull/3394#issuecomment-698196728).

Since lsif-java is under development, I won't harp on this, but what is the current thinking on testing (to catch/avoid regressions) and in future, support stable versions (so we can revert to safe commit versions, in case of regressions)?

**Comment by efritz** [comment]
> Since lsif-java is under development, I won't harp on this, but what is the current thinking on testing (to catch/avoid regressions) and in future, support stable versions (so we can revert to safe commit versions, in case of regressions)?

For the record, we've _yet_ to have a stable version of lsif-java.

**Comment by rvantonder** [comment]
I'm aware that's why I qualified the question with `in future` :-) I'm just trying raise that previously working things are now no longer working, and that happened silently. That's all fine given the flux of the current state of things, but I thought it better to raise than... not say anything.

**Comment by Strum355** [comment]
fwiw this can be fixed by bumping the Spoon version to beta-9 :)
