### ISSUE TITLE
Javadoc links support

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#57]
Javadoc supports linking to classes/methods etc via `{@link ... }`. We should also support this in the LSIF output

See: https://docs.oracle.com/en/java/javase/11/docs/specs/doc-comment-spec.html#link

**Comment by olafurpg** [comment]
Closing this for now since it's a low-priority item and our high-priority goals are ambitious enough. It's worth looking into this again when the sourcegraph backend can consume non-repo sources.
