### ISSUE TITLE
Lombok support

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#64]
Lombok can be used to generate constructors/getters/setters etc through annotation processing at compile time. Without this, there will be errors emitted by javac about symbols not found/wrong args etc. While this doesn't cause any exceptions to be thrown (indexing still works but at somewhat reduced capabilities, to be measured), it should be investigated what the feasibility of doing lombok preprocessing would be and the gains.

https://github.com/georgewfraser/java-language-server/issues/152#issuecomment-680714944

**Comment by olafurpg** [comment]
Closing this issue until we have a reproduction with the new compiler plugin.
