### ISSUE TITLE
Improved support for Bazel

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-java#88]
Related discussions here https://github.com/sourcegraph/sourcegraph/issues/2982#issuecomment-1006670213

At the moment: Bazel requires manual configuration, whereas Maven (for Java) and Gradle (for Java, Scala and Kotlin) just work out-of-the-box without manual configuration.

As per the linked comment:

> Bazel is unlikely to get the same out-of-the-box support as Gradle and Maven because that would eliminate many of the biggest benefits of Bazel: distributed builds and reliable caching

There are a couple of potential options mentioned in that comment; using a `config_setting` or auto-generating `semanticdb` targets. We should:
- [ ] Validate which approach works (or if both work).
- [ ] Add docs on how to set up and maintain lsif-java indexing with Bazel.
- [ ] Document pros and cons of the approach we recommend.

**Comment by olafurpg** [comment]
Fat finger closed this

**Comment by olafurpg** [comment]
Closed by #88, but there is no documentation yet. I opened a separate ticket in https://github.com/sourcegraph/lsif-java/issues/445 to track the addition of docs to the lsif-java website.
